name: expensemanager
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10 # https://pub.dev/packages/dio
  shared_preferences: ^0.5.12+4

  cupertino_icons: ^1.0.0
  google_fonts: 1.1.2
  lottie: 0.7.0+1
  syncfusion_flutter_charts: 18.4.47
  fl_chart: 0.12.3
  carousel_slider: ^3.0.0
  mvc_pattern: ^6.6.4+2
  fluttertoast: ^7.1.8
  email_validator: 1.0.6





dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/cfg/
    - assets/lottie/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
